212 - GE402-TestReportFormat-220330.docx 1 of 1

# Test Report Document

This document is to be prepared by team members who work on “Product Development”.

## Summary

Test report is a document where you document methods/procedures (tests) that are
followed to verify and ensure that your product or system indeed meets the specifications
and other requirements you specified in the “Product Technical Specifications Document”,
and the results of these tests. So you will update your _“_ Test Plan _”_ document to include
the results of the tests. The bold items below should be added to the “Test Plan”.

## Guidelines

1. The document should conform to the GE401-402 document format.
2. The document should include an abstract/summary and an introduction that gives a
    brief description of the product and a brief information related to the document.
3. It is derived from product technical specifications. Therefore, it should address all
    the product specifications related to functions of your product.
4. It should include list of tests to be performed.
5. For each test:
    a. Give the specification/requirement (or specifications/requirements) to be
       tested. (test objective)
    b. Specify test procedure/scenario and pass/fail criteria with quantitative limits.
    c. Determine the responsible team member for the test, test equipment to be
       used (if applicable).
    d. Include the result of the test and a discussion if needed.
6. You should also write a conclusion, which very briefly summarizes the state
    of your development.
7. Do not forget to include a reference section.


