export const TARGET_WORDS_TR = [
    'ABİDE', 'ACEMİ', 'ADRES', 'AHENK', 'AHMET', 'AKREP', 'ALEM', 'ALKIŞ', 'AMBAR', 'ANLIK',
    'ARABA', 'ARMUT', 'ASLAN', 'ASTAR', 'AŞÇI', 'ATLAS', 'AVİZE', 'AYRAN', 'BAHAR', 'BAKIR',
    'BALIK', 'BARIŞ', 'BASIN', 'BAŞAK', 'BEBEK', 'BEDEN', 'BELGE', 'BEYAZ', 'BIÇAK', 'BİBER',
    'BİLET', 'BİLGİ', 'BÖCEK', 'BÖREK', 'BULUT', 'BURSA', 'BUZLU', 'CEKET', 'CEVİZ', 'CİVAR',
    'ÇADIR', 'ÇAKIL', 'ÇANTA', 'ÇARŞI', 'ÇEKİÇ', 'ÇELİK', 'ÇEŞME', 'ÇİÇEK', 'ÇİLEK', 'ÇİZGİ',
    'ÇORAP', 'ÇÖREK', 'DAMLA', 'DAVET', 'DEMİR', 'DENİZ', 'DERGİ', 'DERİN', 'DESTAN', 'DİKEN',
    'DİLEK', 'DİREK', 'DİYAR', 'DOLAP', 'DOMATES', 'DOSYA', 'DÖNER', 'DÖVİZ', 'DUMAN', 'DÜNYA',
    'DÜĞÜN', 'EKMEK', 'ELBİSE', 'ELMA', 'EMLAK', 'ESNAF', 'ETKİN', 'EYLEM', 'EZBER', 'FAKİR',
    'FENER', 'FISTIK', 'FİDAN', 'FİLM', 'FİYAT', 'GAZOZ', 'GEMİ', 'GENİŞ', 'GEYİK', 'GİRİŞ',
    'GİTAR', 'GÖMLEK', 'GÖNÜL', 'GÖREV', 'GÖZLÜK', 'GÜNEŞ', 'GÜZEL', 'HABER', 'HALKA', 'HAMUR',
    'HANIM', 'HARİTA', 'HASAT', 'HASTA', 'HATIR', 'HAVUÇ', 'HAYAL', 'HAYAT', 'HAZIR', 'HEDİYE',
    'HEKİM', 'HELVA', 'HESAP', 'HIRKA', 'HIZLI', 'HİSAR', 'HOROZ', 'HUKUK', 'HUZUR', 'HÜCRE',
    'ILIK', 'IRMAK', 'ISLIK', 'IŞIK', 'İÇERİ', 'İDEAL', 'İDRAR', 'İFADE', 'İHALE', 'İHMAL',
    'İKRAM', 'İLAÇ', 'İLÇE', 'İLKBAHAR', 'İLMEK', 'İMZA', 'İNSAN', 'İNŞAAT', 'İPLİK', 'İSKELE',
    'İSTEK', 'İŞÇİ', 'İZMİR', 'KABAK', 'KAÇAK', 'KADIN', 'KAĞIT', 'KAHVE', 'KALEM', 'KALIP',
    'KANAL', 'KANIT', 'KAPI', 'KARGO', 'KARIN', 'KAŞIK', 'KATIK', 'KAVUN', 'KAYIK', 'KAZAK',
    'KEBAP', 'KEDİ', 'KEFİL', 'KEKİK', 'KELEBEK', 'KEMAN', 'KENAR', 'KENT', 'KESİN', 'KETEN',
    'KILIÇ', 'KIRIK', 'KISIM', 'KIYMA', 'KİBAR', 'KİLİM', 'KİLİT', 'KİMYA', 'KİRAZ', 'KİTAP',
    'KLİMA', 'KOLAY', 'KOLTUK', 'KOMŞU', 'KONUK', 'KORKU', 'KOVA', 'KÖPEK', 'KÖPRÜ', 'KÖY',
    'KREDİ', 'KULAK', 'KUMAŞ', 'KURAL', 'KURGU', 'KURU', 'KUŞAK', 'KUTU', 'KUZEY', 'KÜÇÜK',
    'KÜLTÜR', 'KÜMES', 'KÜREK', 'LİMAN', 'LİMON', 'LİSTE', 'MAHALLE', 'MAKARNA', 'MAKAS', 'MAKİNE',
    'MANAV', 'MANDA', 'MANTO', 'MARUL', 'MASA', 'MASAL', 'MASKE', 'MAYIS', 'MELEK', 'MERAK',
    'MERMİ', 'MESAJ', 'METAL', 'METİN', 'METRO', 'MEVSİM', 'MEYVE', 'MISIR', 'MİMAR', 'MİSAFİR',
    'MODA', 'MODEL', 'MOTOR', 'MUZ', 'MÜZE', 'MÜZİK', 'NABIZ', 'NAKİT', 'NAMAZ', 'NASIR',
    'NAZİK', 'NEFES', 'NEHİR', 'NEMLİ', 'NESNE', 'NÖBET', 'NUMARA', 'OCAK', 'ODA', 'ODUN',
    'OĞLAN', 'OKUL', 'OLAY', 'OLGUN', 'OMUZ', 'ONUR', 'ORMAN', 'ORTAM', 'OYUN', 'ÖDEV',
    'ÖDÜL', 'ÖĞLEN', 'ÖLÇÜ', 'ÖLÜM', 'ÖMÜR', 'ÖNDER', 'ÖNERİ', 'ÖNEM', 'ÖRDEK', 'ÖRNEK',
    'ÖZEL', 'ÖZLEM', 'PAKET', 'PAMUK', 'PARA', 'PARÇA', 'PARK', 'PASTA', 'PATATES', 'PAZAR',
    'PERDE', 'PİLAV', 'PİLOT', 'PİYANO', 'PLAJ', 'PLAK', 'PLAN', 'PLASTİK', 'POLİS', 'PORTAKAL',
    'POSTA', 'PROJE', 'PUAN', 'RADYO', 'RAKİP', 'RAKIM', 'RAPOR', 'REÇEL', 'RENK', 'RESİM',
    'ROMAN', 'ROKET', 'RÜYA', 'RÜZGAR', 'SAAT', 'SABAH', 'SABUN', 'SAÇMA', 'SADIK', 'SAĞLIK',
    'SAHİL', 'SAHNE', 'SAKSI', 'SALATA', 'SALON', 'SAMAN', 'SANAT', 'SANDALYE', 'SANİYE', 'SARAY',
    'SARI', 'SATIŞ', 'SATIR', 'SAVAŞ', 'SAYGI', 'SEBEP', 'SEBZE', 'SEÇİM', 'SEDEF', 'SEVGİ',
    'SEZON', 'SICAK', 'SIFIR', 'SINAV', 'SINIF', 'SIRRA', 'SİLAH', 'SİLGİ', 'SİNEK', 'SİREN',
    'SİRK', 'SİSTEM', 'SİYAH', 'SOFYA', 'SOĞAN', 'SOKAK', 'SOLUK', 'SONUÇ', 'SORU', 'SORUN',
    'SOSİS', 'SOYAD', 'SÖZLÜK', 'SPOR', 'SUÇLU', 'SULTAN', 'SUNUCU', 'SÜPER', 'SÜRAT', 'SÜRÜ',
    'SÜT', 'ŞAHİT', 'ŞAİR', 'ŞAKA', 'ŞAMPIYON', 'ŞAPKA', 'ŞARAP', 'ŞARKI', 'ŞART', 'ŞEHİR',
    'ŞEKER', 'ŞEKİL', 'ŞEMSİYE', 'ŞEREF', 'ŞİFRE', 'ŞİİR', 'ŞİŞE', 'ŞOFÖR', 'ŞUBAT', 'TABAK',
    'TABAN', 'TABLO', 'TADİLAT', 'TAHTA', 'TAKIM', 'TAKVİM', 'TALEBE', 'TALİH', 'TAMİR', 'TANE',
    'TARAK', 'TARİF', 'TARİH', 'TARLA', 'TART', 'TASARIM', 'TAŞIT', 'TATİL', 'TAVAN', 'TAVUK',
    'TAVŞAN', 'TAZE', 'TEKNE', 'TEKERLEK', 'TEKLİF', 'TEKNİK', 'TELEFON', 'TEMEL', 'TEMİZ', 'TEMMUZ',
    'TENİS', 'TEPSİ', 'TERZİ', 'TEST', 'TEYZE', 'TIRTIL', 'TİCARET', 'TİYATRO', 'TOHUM', 'TOPRAK',
    'TORBA', 'TÖREN', 'TRAFİK', 'TREN', 'TURİST', 'TURŞU', 'TUZLU', 'TÜFEK', 'TÜNEL', 'TÜRKÇE',
    'TÜTÜN', 'UÇAK', 'UÇURTMA', 'UFUK', 'UĞUR', 'ULUS', 'UMUT', 'UN', 'UYKU', 'UYUM',
    'UZAK', 'UZAY', 'UZMAN', 'UZUN', 'ÜCRET', 'ÜÇGEN', 'ÜLKE', 'ÜNİTE', 'ÜNLÜ', 'ÜRÜN',
    'ÜSTÜN', 'ÜTÜ', 'ÜZÜM', 'VAGON', 'VAKİT', 'VALİZ', 'VAPUR', 'VARİL', 'VATAN', 'VAZO',
    'VEKİL', 'VERGİ', 'VİDEO', 'VİŞNE', 'VİTRİN', 'VÜCUT', 'YABANCI', 'YAĞMUR', 'YAKIT', 'YALAN',
    'YAMAÇ', 'YANIT', 'YAPRAK', 'YARA', 'YARDIM', 'YARIŞ', 'YASTIK', 'YAŞAM', 'YATAK', 'YAVRU',
    'YAZAR', 'YAZI', 'YEMEK', 'YEMİN', 'YENGEÇ', 'YERLİ', 'YEŞİL', 'YETER', 'YILDIZ', 'YILAN',
    'YOĞURT', 'YOKUŞ', 'YOLCU', 'YORGAN', 'YORUM', 'YÖNETİM', 'YUMURTA', 'YUNUS', 'YURT', 'YUVA',
    'YÜKSEK', 'YÜREK', 'YÜZME', 'YÜZÜK', 'ZAFER', 'ZAMAN', 'ZARAR', 'ZARF', 'ZEHİR', 'ZEKİ',
    'ZEMİN', 'ZEYTİN', 'ZİNCİR', 'ZİYARET', 'ZORLU', 'ZÜRAFA'
].filter(w => w.length === 5); // Ensure all are 5 letters just in case

// For validation, we can use a larger list if available, but for now we'll use the same list or a superset.
// Since I don't have a massive dictionary handy, I'll use the same list for allowed words.
export const ALLOWED_WORDS_TR = [...TARGET_WORDS_TR];
