/** Pixar-style 3D pass (same intent as landing / scrollioGeneratePipeline). */
export const PIXAR_MENTOR_PROMPT = `Transform the attached hand-drawn character into a high-fidelity 3D mascot in authentic Pixar animation style. The final result should feel as if the character belongs inside a Pixar film universe, with warmth, charm, emotional clarity, and cinematic polish.

Treat the drawing as a strict blueprint. Carefully analyze the drawing before generating the 3D version and preserve the exact silhouette, proportions, shape language, and overall structure. Maintain the original color palette exactly as it appears in the drawing, without reinterpretation or stylistic recoloring. All distinctive details, including facial features, accessories, asymmetries, and unique marks, must remain faithful to the original design.

Identify whether the subject is an animal, human, object, or hybrid and recreate it using soft, rounded Pixar-style 3D geometry. The character should feature large, expressive Pixar-style eyes, subtle facial nuance, and a friendly, emotionally readable personality that matches the mood and intention of the original drawing.

All materials and textures must follow Pixar's stylized realism approach. Fur should appear soft and touchable, petals should feel velvety and layered, and skin should be smooth and matte with a handcrafted feel. Surfaces should look warm and premium, avoiding photorealism or plastic-like finishes while remaining believable and rich in detail.

Use Pixar-style cinematic studio lighting to bring the character to life. The lighting should be soft and flattering, similar to clamshell or butterfly lighting, with gentle global illumination and subtle rim light to separate the character from the background while maintaining a friendly, magical atmosphere.

Enhance the drawing with true 3D depth, soft shadows, and natural dimensionality while staying completely faithful to the original design. Pose the character in a joyful, welcoming, high-energy Pixar-style stance that reinforces personality without altering proportions or structure.

Render the final output as a professional Pixar-quality 3D character reveal with ultra-clean presentation and high detail. Use a simple, whimsical, softly blurred background so the mascot remains the clear focus. The final image should feel like a Pixar movie poster or character introduction, presented with cinematic polish and 8K-level clarity.`;

/** LTX 13B distilled image-to-video — full motion / speech prompt (paired with `fal-ai/ltx-video-13b-distilled/image-to-video`). */
export const LTX_IMAGE_TO_VIDEO_PROMPT = `The mascot must clearly appear to be speaking with pronounced, rhythmic mouth movements, opening wide enough to be clearly visible and repeating in continuous talking cycles, including subtle jaw and cheek motion. Avoid minimal or subtle lip movement; the speech animation should be expressive and clearly noticeable. Add natural and clearly visible blinking at regular intervals with smooth eyelid motion (close → brief hold → open), and occasional slight variation in timing to feel natural. Include expressive eye behavior such as slight squinting or widening synchronized with speech. Add slight head movement and small facial micro-expressions while talking. Include gentle idle body motion such as breathing or subtle posture shifts. Animate the environment with soft, subtle motion such as gently swaying elements, floating particles, or light movement to create a lively atmosphere without changing the scene. The camera must remain completely static with no zoom, pan, or shake. Use a high-quality stylized 3D animated look with clean rendering and consistent lighting. Avoid any deformation, flickering, lighting changes, camera movement, stiff animation, or frozen facial expressions. The character should feel like it is actively explaining something to children with clear and engaging speaking animation.`;
